// http://devernay.free.fr/hacks/chip8/C8TECH10.HTM
pub enum InstructionType {
    // using the inst prefix for instructions, allows me to have numbers in enum
    Inst00E0,
    Inst00EE,
    Inst1NNN { nnn: u16 },
    Inst2NNN { nnn: u16 },
    Inst3XNN { x: usize, nn: u8 },
    Inst4XNN { x: usize, nn: u8 },
    Inst5XY0 { x: usize, y: usize },
    Inst6XNN { x: usize, nn: u8 },
    Inst7XNN { x: usize, nn: u8 },
    Inst9XY0 { x: usize, y: usize },
    InstANNN { nnn: u16 },
    InstBNNN { nnn: u16 },
    Inst8XY0 { x: usize, y: usize },
    Inst8XY1 { x: usize, y: usize },
    Inst8XY2 { x: usize, y: usize },
    Inst8XY3 { x: usize, y: usize },
    Inst8XY4 { x: usize, y: usize },
    Inst8XY5 { x: usize, y: usize },
    Inst8XY6 { x: usize, y: usize },
    Inst8XY7 { x: usize, y: usize },
    Inst8XYE { x: usize, y: usize },
}
